name: tokenized-strategy-ape-mix

plugins:
  - name: solidity
  - name: etherscan
  - name: hardhat
  - name: infura
  - name: alchemy
  - name: vyper

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    ref: 4.8.2
  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    ref: test
    contracts_folder: src
    exclude:
      -  src/test/**/*
  - name: periphery
    github: schlagonia/tokenized-strategy-periphery
    ref: master
  - name: yearnvaults
    github: yearn/yearn-vaults
    ref: master

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.2"
    - "@yearnvaults/contracts=yearnvaults/v0.4.6"
    - "@tokenized-strategy=tokenized-strategy/test"
    - "@periphery=periphery/master"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura